# aind manifest for Kubernetes
#
# See README.md for the clusters known to work with.
#
# NOTE: replace "ghcr.io/aind-containers/aind:latest" with "ghcr.io/aind-containers/aind@sha256:<digest>" for reproducible deployment.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aind
  name: aind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aind
  template:
    metadata:
      labels:
        app: aind
    spec:
      initContainers:
      - name: install-kmod
        image: ghcr.io/aind-containers/aind:latest
        command: ["/bin/bash"]
        args: ["-exc", "cp -f /install-kmod.sh /host/tmp/aind-install-kmod.sh && cd /host && chroot . bash /tmp/aind-install-kmod.sh"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: host-root
          mountPath: /host
 # Remounting /sys as read-write in initContainers propagates to the Pod sandbox and the containers.
 # Required by anbox session-manager.
 # https://github.com/aind-containers/aind/issues/21 https://github.com/containerd/containerd/issues/3221 https://github.com/moby/moby/issues/24000#issuecomment-613194003
      - name: fix-sandbox-sysfs
        image: ghcr.io/aind-containers/aind:latest
        command: ["/bin/bash"]
        args: ["-exc", "mount -o remount,rw /sys"]
        securityContext:
          privileged: true
      containers:
      - name: aind
        image: ghcr.io/aind-containers/aind:latest
        tty: true
        securityContext:
          privileged: true
        ports:
        - containerPort: 5900
        volumeMounts:
        - name: host-lib-modules
          readOnly: true
          mountPath: /lib/modules
        resources:
          requests:
            memory: 2048m
            cpu: 500m
        livenessProbe:
          exec:
            command: ["pgrep", "-f", "org.anbox.appmgr"]
          initialDelaySeconds: 20
          periodSeconds: 15
      volumes:
      - name: host-root
        hostPath:
          path: /
      - name: host-lib-modules
        hostPath:
          path: /lib/modules
# NOTE: Set the following nodeSelector if you have non-Ubuntu (i.e. cos) node pools on GKE
#    nodeSelector:
#      cloud.google.com/gke-os-distribution: ubuntu
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: aind
  name: aind
spec:
  ports:
  - port: 5900
    protocol: TCP
  selector:
    app: aind
