#!/bin/bash
set -eux
car=$1
shift
cdr=$@
# machinectl requires absolute path
params=""
avail_envs="INHERIT_DISPLAY DISPLAY CUSTOM_DISPLAY_SCRIPT SESSION_MANAGER_WRAPPER SESSION_MANAGER_ARGS POST_SESSION_SCRIPT"
for name in $avail_envs; do
	[ -n "${!name:-}" ] && params+="--setenv=$name=${!name} "
done
exec machinectl shell $params user@ $(which $car) $cdr

